### ISSUE TITLE
Feature Request: progress indicator!

### ISSUE THREAD

**Issue by drscotthawley** [camenduru/MagicAnimate-colab#2]
(enhancement) 

It would be great if the Colab  featured an indicator of what stage of the computation the code is in, or how many minutes(/hours? days?)  are left.  e.g., a percentage output or progess bar.

(The Gradio "progress bar" doesn't work when you render something for the first time.) 

I don't have my power supply on me, and started the Colab run 18 minutes ago with 20% battery.  It's now down to 5% battery, and I have no idea whether the render will complete in time for me to see it, or if I should just give up until I have a chance to plug in.

**Comment by camenduru** [comment]
thanks for the suggestion ❤ progress bar in the colab cell output
