### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by mp3pintyo** [camenduru/MagicAnimate-colab#5]
This is very strange. Exactly the same error message as your other Google Colab notebooks.
[https://github.com/camenduru/styletts-colab/issues/2](https://github.com/camenduru/styletts-colab/issues/2)

Edge, Chrome (Win11)
Edge, Chrome, Firefox (Win10)

**Comment by mp3pintyo** [comment]
For example, this works without error.
https://github.com/camenduru/style-aligned-colab

**Comment by mp3pintyo** [comment]
Work in Chrome 120.0.6099.63 Win11

**Comment by camenduru** [comment]
thanks ❤
