### ISSUE TITLE
Unable to upload to Motion Sequence

### ISSUE THREAD

**Issue by cedro3** [camenduru/MagicAnimate-colab#7]
On the operation screen, I can upload any still image to Reference Image on the left. However, when I try to upload the Motion Sequence created with DensePose_colab on the right, an error is displayed. Is there any better way?

**Comment by cedro3** [comment]
Solved with the answer to the issue below
UnboundLocalError: local variable 'size' referenced before assignment #6

**Comment by camenduru** [comment]
thanks ❤
